USE cinemadata;

ALTER table actor_imdb
MODIFY COLUMN Nombre VARCHAR(100) NOT NULL,  
MODIFY COLUMN Nacimiento VARCHAR(50),
MODIFY COLUMN Otras_Obras VARCHAR(250),
MODIFY COLUMN Roles VARCHAR(200),
MODIFY COLUMN Premios INT,
MODIFY COLUMN Pelicula VARCHAR(250),
MODIFY COLUMN ID_Pelicula VARCHAR(50),
MODIFY COLUMN Genero_Pelicula VARCHAR(100);

ALTER TABLE actor_imdb
ADD COLUMN Id_Actor INT AUTO_INCREMENT PRIMARY KEY;